modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
    modId="${mod_id}"
    namespace="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    displayURL=""
    issueTrackerURL=""
    authors = "${mod_authors}"
    logoFile = "logo.png"
    description="${mod_description}"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="create"
    mandatory=true
    versionRange="[6.0.6, )"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="kubejs"
    mandatory=false
    versionRange="[2001.6.5-build.16, )"
    ordering="NONE"
    side="BOTH"